name: root-build

schedules:
- cron: "0 3 * * *"
  displayName: Daily build
  branches:
    include:
    - main
  always: true
trigger: none
pr: none

pool:
  vmImage: "ubuntu-20.04"

stages:
  - stage: build
    displayName: Build
    jobs:
      - job: build_prod
        dependsOn: []
        displayName: Build Root Image
        steps:
          - task: Docker@2
            displayName: Login to docker registry
            inputs:
              command: login
              containerRegistry: cccstemp
          - task: Docker@2
            displayName: Build and push nightly image for testing service
            inputs:
              command: buildAndPush
              Dockerfile: pipelines/nightly.Dockerfile
              repository: assemblyline-service-jsjaws-nightly
              tags: stable
              buildContext: "."
              endpoint: cccstemp
